package pizzeria;
//@author Leo

import ar.com.mycompany.entities.DetallePedidos;
import ar.com.mycompany.entities.EstadoPedidos;
import ar.com.mycompany.entities.Pedidos;
import ar.com.mycompany.entities.Pizzas;
import ar.com.mycompany.services.IDetallePedidoService;
import ar.com.mycompany.services.IPedidoService;
import ar.com.mycompany.servicesImp.DetallePedidoService;
import ar.com.mycompany.servicesImp.PedidoService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

public class JFPedido extends javax.swing.JFrame {

    static IPedidoService entityService = new PedidoService();
    static IDetallePedidoService entityDetalle = new DetallePedidoService();
    private DetallePedidos entityD;
    private Pedidos entity;

    private String DetalleB;
    private String PedidosB;

    List<EstadoPedidos> estado = new ArrayList<EstadoPedidos>();
    List<Pizzas> pizzas = new ArrayList<Pizzas>();

    private void loadEntities() {

        DefaultTableModel dt = new DefaultTableModel();
        String[] col = new String[7];
        col[0] = "Pizza";
        dt.setColumnIdentifiers(col);
        col[1] = "Cantidad";
        dt.setColumnIdentifiers(col);
        col[2] = "Precio";
        dt.setColumnIdentifiers(col);
        col[3] = "Total";
        dt.setColumnIdentifiers(col);
        col[4] = "Estado";
        dt.setColumnIdentifiers(col);
        col[5] = "ID";
        dt.setColumnIdentifiers(col);
        col[6] = "IDPedido";
        dt.setColumnIdentifiers(col);

        List<DetallePedidos> result = entity.getDetalle();

        for (DetallePedidos c : result) {

            String[] row = new String[7];
            row[0] = c.getPizza().getNombre();
            row[1] = String.valueOf(c.getCantidad());
            row[2] = String.valueOf(c.getPrecio());
            row[3] = String.valueOf(c.getTotal());
            row[4] = c.getEstadopedidos().getNombre();
            row[5] = String.valueOf(c.getId());
            row[6] = String.valueOf(c.getPedidos().getIdPedidos());
            dt.addRow(row);

        }

        this.jTable1.setModel(dt);

        //jTable1.removeColumn(jTable1.getColumnModel().getColumn(6));
        //jTable1.removeColumn(jTable1.getColumnModel().getColumn(5));
    }

    private void loadCombos() {

        cmbEstado.removeAllItems();

        estado = entityService.getListEstadoPedidos();
        for (EstadoPedidos t : estado) {
            cmbEstado.addItem(t.getNombre());
        }

        cmbPizza.removeAllItems();

        pizzas = entityService.getListPizzas();
        for (Pizzas t : pizzas) {
            cmbPizza.addItem(t.getNombre());
        }
    }

    public JFPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlCliente = new javax.swing.JLabel();
        jlCreacion = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtCreacion = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jlEntrega = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnNewEstPed = new javax.swing.JButton();
        txtExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbPizza = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnNewPizza = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pedidos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jlCliente.setText("Cliente:");

        jlCreacion.setText("Creacion:");

        jlEstado.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jlEntrega.setText("Entrega:");

        jlNumero.setText("Numero:");

        btnNewEstPed.setText("...");
        btnNewEstPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewEstPedMouseClicked(evt);
            }
        });

        txtExit.setText("Cerrar");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle del Pedido", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Pizza:");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Precio:");

        cmbPizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        btnAdd.setText("Agregar");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnNewPizza.setText("...");
        btnNewPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewPizzaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(cmbPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnNewPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel)))
                                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(cmbPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNewPizza))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAdd)
                                        .addComponent(btnCancel)))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jlEstado)
                                                        .addComponent(jlNumero)
                                                        .addComponent(jlEntrega)
                                                        .addComponent(jlCreacion)
                                                        .addComponent(jlCliente))
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(cmbEstado, 0, 262, Short.MAX_VALUE)
                                                        .addComponent(txtNumero)
                                                        .addComponent(txtEntrega, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCreacion, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnNewEstPed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(btnGuardar)
                                                                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtExit)))
                                .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jlCliente)
                                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlCreacion))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlEntrega))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlNumero)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(btnNuevo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnGuardar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlEstado)
                                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNewEstPed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(txtExit)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        entityService.save(entity);
        DetalleB = "";
        PedidosB = "";
        btnNuevoMouseClicked(null);
        /*
        txtCliente.setEditable(false);
        txtCreacion.setEditable(false);
        txtEntrega.setEditable(false);
        txtNumero.setEditable(false);
        cmbEstado.setEditable(false);
        btnNewEstPed.setVisible(false);
        btnNewPizza.setVisible(false);
        cmbPizza.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtCant.setEnabled(false);
         */
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        btnNuevoMouseClicked(null);

    }//GEN-LAST:event_formWindowOpened

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked

        Date date = Calendar.getInstance().getTime();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = formatter.format(date);

        txtCliente.setText("");
        txtNumero.setText("");
        txtCreacion.setText(strDate);
        txtEntrega.setText(strDate);
        btnCancel.setEnabled(false);

        entity = new Pedidos();

        loadCombos();
        loadEntities();

    }//GEN-LAST:event_btnNuevoMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        Integer row = jTable1.getSelectedRow();

        DetalleB = ((String) jTable1.getModel().getValueAt(row, 5));
        PedidosB = ((String) jTable1.getModel().getValueAt(row, 6));

        entity = entityService.find(Integer.parseInt(PedidosB));
        txtPrecio.setText(String.valueOf((String) jTable1.getModel().getValueAt(row, 2)));
        txtCant.setText(String.valueOf((String) jTable1.getModel().getValueAt(row, 1)));

        /*
        for (int i = 1; i <= pizzas.size(); i++) {
            if (pizzas.get(i - 1).getId() == linea.getPizza().getId()) {
                cmbPizza.setSelectedIndex(i - 1);
                break;
            }

        }
         */
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyCode() == 127) {

            JDialog.setDefaultLookAndFeelDecorated(true);
            int response = JOptionPane.showConfirmDialog(null, "Seguro desea eliminar el registro? ", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {

                Integer row = jTable1.getSelectedRow();
                DetalleB = ((String) jTable1.getModel().getValueAt(row, 5));
                entityD = entityDetalle.find(Integer.parseInt(DetalleB));
                entityDetalle.delete(entityD);

                entity = entityService.find(Integer.parseInt(PedidosB));
                //entityService.delete(entity);
                loadEntities();

            }

        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void btnNewEstPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewEstPedMouseClicked
        new JFEstadoPedidos().setVisible(true);
    }//GEN-LAST:event_btnNewEstPedMouseClicked

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked


        try {

            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

            entity.setFechaHoraCreacion(formatter.parse(txtCreacion.getText()));
            entity.setFechaHoraEntrega(formatter.parse(txtEntrega.getText()));

            entity.setNombreCliente(txtCliente.getText());
            entity.setEstadopedidos(estado.get(cmbEstado.getSelectedIndex()));
            entity.setNumeroPedidos(Integer.valueOf(txtNumero.getText()));

            DetallePedidos linea = new DetallePedidos();

            linea.setPizza(pizzas.get(cmbPizza.getSelectedIndex()));
            linea.setCantidad(Integer.parseInt(txtCant.getText()));
            linea.setPrecio(Double.parseDouble(txtPrecio.getText()));
            linea.setTotal(linea.getPrecio() * linea.getCantidad());
            linea.setEstadopedidos(estado.get(cmbEstado.getSelectedIndex()));
            linea.setPedidos(entity);

            entity.getDetalle().add(linea);
            entityService.save(entity);
            loadEntities();

            txtPrecio.setText("");
            txtCant.setText("");
            btnCancel.setEnabled(true);

        } catch (NumberFormatException | ParseException e) {
            JOptionPane.showMessageDialog(txtNumero, e);

        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnNewPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewPizzaMouseClicked
        new JFPizza().setVisible(true);
    }//GEN-LAST:event_btnNewPizzaMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked

        btnCancel.setEnabled(false);
        JDBuscarFactura c = new JDBuscarFactura(this, true);
        c.setVisible(true);

        if (c.idPed > 0) {

            entity = entityService.find(c.idPed);

            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

            txtCreacion.setText(formatter.format(entity.getFechaHoraCreacion()));
            txtEntrega.setText(formatter.format(entity.getFechaHoraEntrega()));

            txtCliente.setText(entity.getNombreCliente());
            txtNumero.setText(String.valueOf(entity.getNumeroPedidos()));

            for (int i = 1; i <= estado.size(); i++) {
                if (estado.get(i - 1).getIdEstadoPedidos() == entity.getEstadopedidos().getIdEstadoPedidos()) {
                    cmbEstado.setSelectedIndex(i - 1);
                    break;
                }

            }

            loadEntities();

        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        PedidosB = ((String) jTable1.getModel().getValueAt(0, 6));
        System.out.println(PedidosB);
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            DetalleB = ((String) jTable1.getModel().getValueAt(i, 5));
            entityD = entityDetalle.find(Integer.parseInt(DetalleB));
            entityDetalle.delete(entityD);
            System.out.println(DetalleB + " " + PedidosB);
        }
        System.out.println(PedidosB);
        entity = entityService.find(Integer.parseInt(PedidosB));
        entityService.delete(entity);
        btnNuevoMouseClicked(null);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNewEstPed;
    private javax.swing.JButton btnNewPizza;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbPizza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlCreacion;
    private javax.swing.JLabel jlEntrega;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCreacion;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JButton txtExit;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
