package pizzeria;
//@author Leo

import ar.com.mycompany.entities.Pizzas;
import ar.com.mycompany.entities.TamanioPizzas;
import ar.com.mycompany.entities.TipoPizzas;
import ar.com.mycompany.entities.VariedadPizzas;
import ar.com.mycompany.services.IPizzaService;
import ar.com.mycompany.servicesImp.PizzaService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class JFPizza extends javax.swing.JFrame {
    
    static IPizzaService entityService = new PizzaService();
    private Pizzas entity;

    private List<TipoPizzas> tipo = new ArrayList<>();
    private List<VariedadPizzas> variedad = new ArrayList<>();
    private List<TamanioPizzas> tamanio = new ArrayList<>();

    private void loadEntities() {
        DefaultTableModel dt = new DefaultTableModel();
        String[] col = new String[6];
        col[0] = "Id";
        dt.setColumnIdentifiers(col);
        col[1] = "Nombre";
        dt.setColumnIdentifiers(col);
        col[2] = "Precio";
        dt.setColumnIdentifiers(col);
        col[3] = "Tipo";
        dt.setColumnIdentifiers(col);
        col[4] = "Variedad";
        dt.setColumnIdentifiers(col);
        col[5] = "Tamaño";
        dt.setColumnIdentifiers(col);

        List<Pizzas> result = entityService.getAll();

        for (Pizzas c : result) {
            String[] row = new String[6];
            row[0] = String.valueOf(c.getId());
            row[1] = c.getNombre();
            row[2] = String.valueOf(c.getPrecio());
            row[3] = c.getTipopizza().getNombre();
            row[4] = c.getVariedadpizza().getNombre();
            row[5] = c.getTamaniopizza().getNombre();
            dt.addRow(row);
        }
        this.jTable1.setModel(dt);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));

    }

    private void loadCombos() {

        cmbTipo.removeAllItems();
        cmbVariedad.removeAllItems();
        cmbTamanio.removeAllItems();

        tipo = entityService.getListTipoPizzas();
        for (TipoPizzas t : tipo) {
            cmbTipo.addItem(t.getNombre());
        }

        variedad = entityService.getListVariedadPizzas();
        for (VariedadPizzas t : variedad) {
            cmbVariedad.addItem(t.getNombre());
        }

        tamanio = entityService.getListTamanioPizzas();
        for (TamanioPizzas t : tamanio) {
            cmbTamanio.addItem(t.getNombre());
        }
    }

    public JFPizza() {
        initComponents();
        idPizza.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPizza = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlVariedad = new javax.swing.JLabel();
        jlTamanio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbVariedad = new javax.swing.JComboBox<>();
        cmbTamanio = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNewTipo = new javax.swing.JButton();
        btnNewVariedad = new javax.swing.JButton();
        btnNewTaman = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pizzas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        idPizza.setEnabled(false);

        jlNombre.setText("Nombre:");

        jlPrecio.setText("Precio:");

        jlTipo.setText("Tipo:");

        jlVariedad.setText("Variedad:");

        jlTamanio.setText("Tamaño:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbVariedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnNewTipo.setText("...");
        btnNewTipo.setMaximumSize(new java.awt.Dimension(45, 20));
        btnNewTipo.setMinimumSize(new java.awt.Dimension(45, 20));
        btnNewTipo.setPreferredSize(new java.awt.Dimension(45, 20));
        btnNewTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewTipoMouseClicked(evt);
            }
        });

        btnNewVariedad.setText("...");
        btnNewVariedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewVariedadMouseClicked(evt);
            }
        });

        btnNewTaman.setText("...");
        btnNewTaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewTamanMouseClicked(evt);
            }
        });

        btnExit.setText("Cerrar");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombre)
                                    .addComponent(jlPrecio)
                                    .addComponent(jlTipo))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(cmbTipo, 0, 205, Short.MAX_VALUE)
                                    .addComponent(txtPrecio)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlVariedad)
                                    .addComponent(jlTamanio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbVariedad, 0, 204, Short.MAX_VALUE)
                                    .addComponent(cmbTamanio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(idPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNewVariedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNewTaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNewTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPrecio)
                            .addComponent(btnGuardar)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlVariedad)
                    .addComponent(cmbVariedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewVariedad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNewTaman, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlTamanio))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        if (txtNombre.getText().equals("")) {
            return;
        }

        if (txtPrecio.getText().equals("")) {
            return;
        }

        if (idPizza.getText().equals("0")) {

            entity = new Pizzas();

        } else {

            entity = entityService.find(Integer.parseInt(idPizza.getText()));

        }

        try {

            entity.setNombre(txtNombre.getText());
            entity.setPrecio(Double.parseDouble(txtPrecio.getText()));

            entity.setTipopizza(tipo.get(cmbTipo.getSelectedIndex()));
            entity.setVariedadpizza(variedad.get(cmbVariedad.getSelectedIndex()));
            entity.setTamaniopizza(tamanio.get(cmbTamanio.getSelectedIndex()));

            entityService.save(entity);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(txtPrecio, "El precio no puede ser texto o estar en blanco");
            return;

        }

        txtNombre.setText("");
        txtPrecio.setText("");
        idPizza.setText("0");

        txtNombre.setEditable(false);
        txtPrecio.setEditable(false);
        cmbTipo.setEditable(false);
        cmbVariedad.setEditable(false);
        cmbTamanio.setEditable(false);

        loadEntities();

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        loadEntities();
        loadCombos();

        txtNombre.setEditable(false);
        txtPrecio.setEditable(false);
        cmbTipo.setEnabled(false);
        cmbVariedad.setEnabled(false);
        cmbTamanio.setEnabled(false);
        btnNewTaman.setVisible(false);
        btnNewTipo.setVisible(false);
        btnNewVariedad.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked

        txtNombre.setText("");
        txtPrecio.setText("");
        idPizza.setText("0");
        txtNombre.setEditable(true);
        txtPrecio.setEditable(true);
        txtNombre.requestFocus();
        cmbTipo.setEnabled(true);
        cmbVariedad.setEnabled(true);
        cmbTamanio.setEnabled(true);
        btnNewTaman.setVisible(true);
        btnNewTipo.setVisible(true);
        btnNewVariedad.setVisible(true);

    }//GEN-LAST:event_btnNuevoMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        Integer row = jTable1.getSelectedRow();
        idPizza.setText((String) jTable1.getModel().getValueAt(row, 0));
        entity = entityService.find(Integer.parseInt(idPizza.getText()));
        txtNombre.setText(entity.getNombre());
        txtPrecio.setText(String.valueOf(entity.getPrecio()));
        
        for (int i = 1; i <= tipo.size(); i++) {
            if (tipo.get(i - 1).getId() == entity.getTipopizza().getId()) {
                cmbTipo.setSelectedIndex(i - 1);
                break;
            }

        }

        for (int i = 1; i <= variedad.size(); i++) {
            if (variedad.get(i - 1).getId() == entity.getVariedadpizza().getId()) {
                cmbVariedad.setSelectedIndex(i - 1);
                break;
            }

        }

        for (int i = 1; i <= tamanio.size(); i++) {
            if (tamanio.get(i - 1).getId() == entity.getTamaniopizza().getId()) {
                cmbTamanio.setSelectedIndex(i - 1);
                break;
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyCode() == 127) {

            JDialog.setDefaultLookAndFeelDecorated(true);
            int response = JOptionPane.showConfirmDialog(null, "Seguro desea eliminar el registro? ", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {

                Integer row = jTable1.getSelectedRow();
                idPizza.setText((String) jTable1.getModel().getValueAt(row, 0));
                entity = entityService.find(Integer.parseInt(idPizza.getText()));
                entityService.delete(entity);
                loadEntities();

            }

        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void btnNewTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewTipoMouseClicked

        new JFTiposPizzas().setVisible(true);

    }//GEN-LAST:event_btnNewTipoMouseClicked

    private void btnNewVariedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewVariedadMouseClicked

        new JFVariedadPizzas().setVisible(true);

    }//GEN-LAST:event_btnNewVariedadMouseClicked

    private void btnNewTamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewTamanMouseClicked

        new JFTamanioPizzas().setVisible(true);

    }//GEN-LAST:event_btnNewTamanMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFPizza().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNewTaman;
    private javax.swing.JButton btnNewTipo;
    private javax.swing.JButton btnNewVariedad;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbTamanio;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmbVariedad;
    private javax.swing.JLabel idPizza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlTamanio;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlVariedad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
